import { createElement } from 'react';
import { docs } from '@/.source/server';
import { loader } from 'fumadocs-core/source';
import { Pic } from '@/components/icons';

/**
 * The single content source. `@/.source/server` is generated by `fumadocs-mdx`
 * (postinstall / the next plugin) from `content/docs` + `source.config.ts`.
 *
 * `icon` resolves a section's `meta.json` `icon` string to one of the crafted
 * publishing glyphs (components/icons.tsx) so the sidebar reads as the brand
 * SideNav — a publishing mark beside each section.
 */
export const source = loader({
  baseUrl: '/docs',
  icon(icon) {
    if (!icon) return undefined;
    return createElement(Pic, { name: icon, size: 16 });
  },
  source: docs.toFumadocsSource(),
});
