import { docs } from '@/.source/server';
import { loader } from 'fumadocs-core/source';

/**
 * The single content source. `@/.source/server` is generated by `fumadocs-mdx`
 * (postinstall / the next plugin) from `content/docs` + `source.config.ts`.
 */
export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
});
